from PyQt5 import QtCore, QtGui, QtWidgets
import resource
from PyQt5.QtWidgets import *
import sys

class Home(QMainWindow):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 833)
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(Dialog)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/menu-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setCheckable(True)
        self.menu_btn.setAutoExclusive(True)
        self.menu_btn.setObjectName("menu_btn")
        self.verticalLayout.addWidget(self.menu_btn)
        self.home_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/house-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/house-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn.setIcon(icon1)
        self.home_btn.setCheckable(True)
        self.home_btn.setAutoExclusive(True)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout.addWidget(self.home_btn)
        self.pdf_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.pdf_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/pdf-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/pdf-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pdf_btn.setIcon(icon2)
        self.pdf_btn.setCheckable(True)
        self.pdf_btn.setAutoExclusive(True)
        self.pdf_btn.setObjectName("pdf_btn")
        self.verticalLayout.addWidget(self.pdf_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 650, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.setting_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.setting_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/settings-9-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/settings-9-24 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.setting_btn.setIcon(icon3)
        self.setting_btn.setCheckable(True)
        self.setting_btn.setAutoExclusive(True)
        self.setting_btn.setObjectName("setting_btn")
        self.verticalLayout_3.addWidget(self.setting_btn)
        self.logout_btn = QtWidgets.QPushButton(self.icon_only_widget)
        self.logout_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/logout-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon4)
        self.logout_btn.setCheckable(True)
        self.logout_btn.setAutoExclusive(True)
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_3.addWidget(self.logout_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.icon_only_widget, 1, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(Dialog)
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_arrow_btn = QtWidgets.QPushButton(self.full_menu_widget)
        self.left_arrow_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_arrow_btn.setIcon(icon5)
        self.left_arrow_btn.setIconSize(QtCore.QSize(14, 14))
        self.left_arrow_btn.setCheckable(True)
        self.left_arrow_btn.setAutoExclusive(True)
        self.left_arrow_btn.setObjectName("left_arrow_btn")
        self.verticalLayout_2.addWidget(self.left_arrow_btn)
        self.home_btn_1 = QtWidgets.QPushButton(self.full_menu_widget)
        self.home_btn_1.setIcon(icon1)
        self.home_btn_1.setIconSize(QtCore.QSize(14, 14))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout_2.addWidget(self.home_btn_1)
        self.pdf_btn_1 = QtWidgets.QPushButton(self.full_menu_widget)
        self.pdf_btn_1.setIcon(icon2)
        self.pdf_btn_1.setIconSize(QtCore.QSize(14, 14))
        self.pdf_btn_1.setCheckable(True)
        self.pdf_btn_1.setAutoExclusive(True)
        self.pdf_btn_1.setObjectName("pdf_btn_1")
        self.verticalLayout_2.addWidget(self.pdf_btn_1)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 655, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.setting_btn_1 = QtWidgets.QPushButton(self.full_menu_widget)
        self.setting_btn_1.setIcon(icon3)
        self.setting_btn_1.setIconSize(QtCore.QSize(14, 14))
        self.setting_btn_1.setCheckable(True)
        self.setting_btn_1.setAutoExclusive(True)
        self.setting_btn_1.setObjectName("setting_btn_1")
        self.verticalLayout_4.addWidget(self.setting_btn_1)
        self.logout_btn_1 = QtWidgets.QPushButton(self.full_menu_widget)
        self.logout_btn_1.setIcon(icon4)
        self.logout_btn_1.setIconSize(QtCore.QSize(14, 14))
        self.logout_btn_1.setCheckable(True)
        self.logout_btn_1.setAutoExclusive(True)
        self.logout_btn_1.setObjectName("logout_btn_1")
        self.verticalLayout_4.addWidget(self.logout_btn_1)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.full_menu_widget, 1, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(Dialog)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.titlebar = QtWidgets.QWidget(self.widget_5)
        self.titlebar.setObjectName("titlebar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titlebar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(1011, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_btn = QtWidgets.QPushButton(self.titlebar)
        self.minimize_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon6)
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.titlebar)
        self.maximize_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize_btn.setIcon(icon7)
        self.maximize_btn.setObjectName("maximize_btn")
        self.horizontalLayout.addWidget(self.maximize_btn)
        self.close_btn = QtWidgets.QPushButton(self.titlebar)
        self.close_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon8)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.titlebar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label_4 = QtWidgets.QLabel(self.home_page)
        self.label_4.setGeometry(QtCore.QRect(320, 100, 361, 371))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icon/icons/add-file.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.result_cpn_widget = QtWidgets.QWidget(self.home_page)
        self.result_cpn_widget.setGeometry(QtCore.QRect(660, 10, 451, 751))
        self.result_cpn_widget.setObjectName("result_cpn_widget")
        self.save_btn = QtWidgets.QPushButton(self.result_cpn_widget)
        self.save_btn.setGeometry(QtCore.QRect(170, 520, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_btn.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/pdf-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon9)
        self.save_btn.setAutoExclusive(False)
        self.save_btn.setDefault(False)
        self.save_btn.setFlat(False)
        self.save_btn.setObjectName("save_btn")
        self.result_lbl = QtWidgets.QLabel(self.result_cpn_widget)
        self.result_lbl.setGeometry(QtCore.QRect(120, 40, 229, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(19)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.result_lbl.setFont(font)
        self.result_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.result_lbl.setScaledContents(True)
        self.result_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lbl.setObjectName("result_lbl")
        self.layoutWidget_2 = QtWidgets.QWidget(self.result_cpn_widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(130, 150, 271, 132))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.cpn_value = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.cpn_value.setContentsMargins(15, 15, 15, 15)
        self.cpn_value.setSpacing(15)
        self.cpn_value.setObjectName("cpn_value")
        self.covid_19 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.covid_19.setFont(font)
        self.covid_19.setObjectName("covid_19")
        self.cpn_value.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.covid_19)
        self.covid_value = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.covid_value.setFont(font)
        self.covid_value.setObjectName("covid_value")
        self.cpn_value.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.covid_value)
        self.pneumonia = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pneumonia.setFont(font)
        self.pneumonia.setObjectName("pneumonia")
        self.cpn_value.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pneumonia)
        self.pneumonia_value = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pneumonia_value.setFont(font)
        self.pneumonia_value.setObjectName("pneumonia_value")
        self.cpn_value.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pneumonia_value)
        self.normal_value = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.normal_value.setFont(font)
        self.normal_value.setObjectName("normal_value")
        self.cpn_value.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.normal_value)
        self.normal = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.normal.setFont(font)
        self.normal.setObjectName("normal")
        self.cpn_value.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.normal)
        self.layoutWidget = QtWidgets.QWidget(self.result_cpn_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 320, 229, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.save_form = QtWidgets.QFormLayout(self.layoutWidget)
        self.save_form.setContentsMargins(15, 15, 15, 15)
        self.save_form.setSpacing(15)
        self.save_form.setObjectName("save_form")
        self.age = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.age.setFont(font)
        self.age.setObjectName("age")
        self.save_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.age)
        self.age_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.age_spinBox.setFont(font)
        self.age_spinBox.setObjectName("age_spinBox")
        self.save_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.age_spinBox)
        self.phone = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.save_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.phone_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_lineEdit.setFont(font)
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.save_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.phone_lineEdit)
        self.name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.save_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name)
        self.name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setText("")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.save_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.widget_2 = QtWidgets.QWidget(self.result_cpn_widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_14.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/cil-chevron-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setIconSize(QtCore.QSize(10, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.save_error = QtWidgets.QLabel(self.result_cpn_widget)
        self.save_error.setGeometry(QtCore.QRect(130, 590, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.save_error.setFont(font)
        self.save_error.setAlignment(QtCore.Qt.AlignCenter)
        self.save_error.setObjectName("save_error")
        self.predict_btn = QtWidgets.QPushButton(self.home_page)
        self.predict_btn.setGeometry(QtCore.QRect(420, 480, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.predict_btn.setFont(font)
        self.predict_btn.setObjectName("predict_btn")
        self.file_error = QtWidgets.QLabel(self.home_page)
        self.file_error.setGeometry(QtCore.QRect(390, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.file_error.setFont(font)
        self.file_error.setAlignment(QtCore.Qt.AlignCenter)
        self.file_error.setObjectName("file_error")
        self.stackedWidget.addWidget(self.home_page)
        self.pdf_page = QtWidgets.QWidget()
        self.pdf_page.setObjectName("pdf_page")
        self.widget = QtWidgets.QWidget(self.pdf_page)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1101, 751))
        self.widget.setObjectName("widget")
        self.table_header = QtWidgets.QTableWidget(self.widget)
        self.table_header.setGeometry(QtCore.QRect(80, 20, 951, 661))
        self.table_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_header.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_header.setShowGrid(False)
        self.table_header.setWordWrap(True)
        self.table_header.setRowCount(2)
        self.table_header.setObjectName("table_header")
        self.table_header.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_header.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_header.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_header.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_header.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon9)
        self.table_header.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/download-2-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.table_header.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon9)
        self.table_header.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_header.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon11)
        self.table_header.setItem(1, 3, item)
        self.table_header.horizontalHeader().setDefaultSectionSize(220)
        self.table_header.horizontalHeader().setSortIndicatorShown(True)
        self.table_header.horizontalHeader().setStretchLastSection(True)
        self.table_header.verticalHeader().setDefaultSectionSize(70)
        self.table_header.verticalHeader().setMinimumSectionSize(30)
        self.stackedWidget.addWidget(self.pdf_page)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_5, 1, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.left_arrow_btn.clicked['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.menu_btn.clicked['bool'].connect(self.full_menu_widget.setVisible) # type: ignore
        self.left_arrow_btn.clicked['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.close_btn.clicked['bool'].connect(Dialog.close) # type: ignore
        self.pdf_btn.toggled['bool'].connect(self.pdf_btn_1.setChecked) # type: ignore
        self.setting_btn.toggled['bool'].connect(self.setting_btn_1.setChecked) # type: ignore
        self.logout_btn.toggled['bool'].connect(self.logout_btn_1.setChecked) # type: ignore
        self.menu_btn.clicked['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.home_btn_1.toggled['bool'].connect(self.home_btn.setChecked) # type: ignore
        self.home_btn.toggled['bool'].connect(self.home_btn_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.home_btn_1.setText(_translate("Dialog", "Home"))
        self.pdf_btn_1.setText(_translate("Dialog", "Saved Files"))
        self.setting_btn_1.setText(_translate("Dialog", "Setting"))
        self.logout_btn_1.setText(_translate("Dialog", "Logout"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.result_lbl.setText(_translate("Dialog", "R e s u l t"))
        self.covid_19.setText(_translate("Dialog", "Covid-19 :"))
        self.covid_value.setText(_translate("Dialog", "TextLabel"))
        self.pneumonia.setText(_translate("Dialog", "Pneumonia :"))
        self.pneumonia_value.setText(_translate("Dialog", "TextLabel"))
        self.normal_value.setText(_translate("Dialog", "TextLabel"))
        self.normal.setText(_translate("Dialog", "Normal :"))
        self.age.setText(_translate("Dialog", "Age :"))
        self.phone.setText(_translate("Dialog", "Phone :"))
        self.phone_lineEdit.setPlaceholderText(_translate("Dialog", "Phone Number"))
        self.name.setText(_translate("Dialog", "Name :"))
        self.name_lineEdit.setPlaceholderText(_translate("Dialog", "Patient Name"))
        self.save_error.setText(_translate("Dialog", "Name is required"))
        self.predict_btn.setText(_translate("Dialog", "Predict"))
        self.file_error.setText(_translate("Dialog", "File type not alloewed"))
        self.table_header.setSortingEnabled(True)
        item = self.table_header.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.table_header.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.table_header.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "File Name"))
        item = self.table_header.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Date"))
        item = self.table_header.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Action"))
        __sortingEnabled = self.table_header.isSortingEnabled()
        self.table_header.setSortingEnabled(False)
        item = self.table_header.item(0, 1)
        item.setText(_translate("Dialog", "Dev-Oza-111111111.pdf"))
        item = self.table_header.item(0, 2)
        item.setText(_translate("Dialog", "15-11-2006"))
        item = self.table_header.item(1, 1)
        item.setText(_translate("Dialog", "Anish-Giri-44444444444444444444.pdf"))
        item = self.table_header.item(1, 2)
        item.setText(_translate("Dialog", "1-2-2000"))
        self.table_header.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)

    with open ("style.qss", "r") as f:
        app.setStyleSheet(f.read())

    home = QtWidgets.QWidget()
    ui = Home()
    ui.setupUi(home)
    ui.full_menu_widget.hide()
    ui.home_btn.setChecked(True)
    ui.stackedWidget.setCurrentIndex(0)
    home.show()
    sys.exit(app.exec_())
